config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :workfiles
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "workfiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :workfile, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workfile.rb
class Workfile < ApplicationRecord
  has_many :records, dependent: :destroy
  accepts_nested_attributes_for :records, allow_destroy: true, reject_if: :all_blank
  #accepts_nested_attributes_for :records, allow_destroy: true, reject_if: proc { |att| att['date'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:description, :ordernumber, :date, :begin_time, :end_time, :user_id, :workfile_id)
    end
end

app/controllers/workfiles_controller.rb
class WorkfilesController < ApplicationController
  before_action :set_workfile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /workfiles
  # GET /workfiles.json
  def index
    @workfiles = Workfile.all
  end

  # GET /workfiles/1
  # GET /workfiles/1.json
  def show
  end

  # GET /workfiles/new
  def new
    @workfile = Workfile.new
    #@workfile.records.build
  end

  # GET /workfiles/1/edit
  def edit
    #@workfile.records.build
  end

  # POST /workfiles
  # POST /workfiles.json
  def create
    @workfile = Workfile.new(workfile_params)

    respond_to do |format|
      if @workfile.save
        format.html { redirect_to @workfile, notice: 'Workfile was successfully created.' }
        format.json { render :show, status: :created, location: @workfile }
      else
        format.html { render :new }
        format.json { render json: @workfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workfiles/1
  # PATCH/PUT /workfiles/1.json
  def update
    respond_to do |format|
      if @workfile.update(workfile_params)
        format.html { redirect_to @workfile, notice: 'Workfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @workfile }
      else
        format.html { render :edit }
        format.json { render json: @workfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workfiles/1
  # DELETE /workfiles/1.json
  def destroy
    @workfile.destroy
    respond_to do |format|
      format.html { redirect_to workfiles_url, notice: 'Workfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workfile
      @workfile = Workfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workfile_params
      # params.require(:workfile).permit(:title, :description, :date, :user_id)
      # params.require(:todo_list).permit(:name, tasks_attributes: [:id, :_destroy, :todo_list_id, :name, :completed, :due])
      params.require(:workfile).permit(:title, :description, :date, :user_id, records_attributes: Record.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/workfiles_helper.rb
module WorkfilesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Time-Rec
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Time-Rec", root_path

        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Neuer Stundennachweis", new_workfile_path
            - if current_user.try(:admin?)
              %li= link_to "Administration", users_path
            %li= link_to t("Sign Out"), destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            -# = %li= link_to t("Sign Up"), new_user_registration_path
            %li= link_to t("Sign In"), new_user_session_path
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

      = yield

app/views/records/_form.html.erb
<%= simple_form_for(@record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :ordernumber %>
    <%= f.input :date %>
    <%= f.input :begin_time %>
    <%= f.input :end_time %>
    <%= f.input :user_id %>
    <%= f.association :workfile %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Ordernumber</th>
      <th>Date</th>
      <th>Begin time</th>
      <th>End time</th>
      <th>User</th>
      <th>Workfile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.description %></td>
        <td><%= record.ordernumber %></td>
        <td><%= record.date %></td>
        <td><%= record.begin_time %></td>
        <td><%= record.end_time %></td>
        <td><%= record.user_id %></td>
        <td><%= record.workfile %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Ordernumber:</strong>
  <%= @record.ordernumber %>
</p>

<p>
  <strong>Date:</strong>
  <%= @record.date %>
</p>

<p>
  <strong>Begin time:</strong>
  <%= @record.begin_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @record.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @record.user_id %>
</p>

<p>
  <strong>Workfile:</strong>
  <%= @record.workfile %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/workfiles/_form.html.haml
.workfile
  = simple_form_for(@workfile) do |f|
    = f.error_notification
    .form-inputs
      = f.input :title
      = f.input :date
      = f.input :description
    %table.table
      %thead
        %tr
          %th Ordernumber
          %th Description
          %th Date
          %th Start
          %th End
      %tbody.fields
        = f.simple_fields_for :records do |builder|
          = render 'record', f: builder
    .form-actions
      = f.button :submit
      = link_to_add_row('Add Record', f, :records, class: 'btn btn-primary')

app/views/workfiles/_record.html.haml
%tr
  %td= f.input :ordernumber, label: false, as: :string
  %td= f.input :description, label: false
  %td= f.input :date, label: false, as: :date
  %td= f.input :begin_time, label: false, as: :time
  %td= f.input :end_time, label: false, as: :time
  %td
    = f.input_field :_destroy, as: :hidden
    = link_to 'Delete', '#', class: 'btn btn-default btn-xs'

app/views/workfiles/edit.html.erb
<h1>Editing Workfile</h1>

<%= render 'form', workfile: @workfile %>

<%= link_to 'Show', @workfile %> |
<%= link_to 'Back', workfiles_path %>

app/views/workfiles/index.html.haml
%h1 Workfiles
.panel.panel-default
  .panel-body
    .workfile
      %table
        %thead
          %tr
            %th Title
            %th Description
            %th Date
            %th User
            %th{:colspan => "3"}
        %tbody
          - @workfiles.each do |workfile|
            %tr
              %td= workfile.title
              %td= workfile.description
              %td= workfile.date
              %td= workfile.user_id
              %td= link_to 'Show', workfile
              %td= link_to 'Edit', edit_workfile_path(workfile)
              %td= link_to 'Destroy', workfile, method: :delete, data: { confirm: 'Are you sure?' }
      %br/
      = link_to 'New Workfile', new_workfile_path

app/views/workfiles/new.html.haml
%legend New Workfile
= render 'form', workfile: @workfile
= link_to "Back", root_path, class: "btn btn-default"

app/views/workfiles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @workfile.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workfile.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @workfile.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @workfile.user_id %>
</p>

<%= link_to 'Edit', edit_workfile_path(@workfile) %> |
<%= link_to 'Back', workfiles_path %>